version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=cine_prn335

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "cine@prn.com"
      PGADMIN_DEFAULT_PASSWORD: "abc123"
    ports:
      - "80:80"
    depends_on:
      - postgres